### ISSUE TITLE
Feature Request: Use "Vector SDK App" with Anki's SDK Credentials

### ISSUE THREAD

**Issue by Skybird129** [kercre123/wire-prod-pod#15]
Hi,

I'm very exited how quick features are added to wire-pod and wire-prod pod and wire and all contributors are doing an awesome job. Thank you very much.

As far as I understand, the new "Vector SDK App" feature found under "Configure bot settings (similar to Vector mobile app)" works only after clearing user data on prod bots or strange errors might occur. In addition, they must be connected again after every restart. 
(I don't know yet, how to connect a prod bot, whose user data has not been cleared, as the serial is not appearing on the page.)

I'd like to propose an idea. In my opinion I think quite a few people (including me and my family) have grown attached to our Vectors and really don't want to clear user data. However, if the bot already had an account with Anki or ddl and Anki's Vector Python SDK was configured prior to moving Vector to wire-prod-pod, the .anki_vector directory is available, including the bots cert and the GUID inside sdk_config.ini. 

Could these credentials be used to connect to a prod Vector automatically, without having to reconnect every reboot or having to clear user data?

**Comment by kercre123** [comment]
To connect a bot, use [vector-epod-setup](https://keriganc.com/vector-epod-setup) and follow the instructions. On a bot whose userdata hasn't been cleared, you may have to press "ACTIVATE" a few times. The authentication may only be temporary.

I am still trying to figure out how to use those certs to my advantage

**Comment by Skybird129** [comment]
When I initially moved my Vectors to wire-prod-pod, I used [https://www.project-victor.org/noflow-devsetup](https://www.project-victor.org/noflow-devsetup) as was stated in the readme during that time to install the Escape Pod OTA. I never considered or used vector-epod-setup, because the Vectors were already on EP firmware. What does "ACTIVATE" actually do? Do I have to put the Vectors in recovery mode? Can I activate them using my laptop or do I have to run vector-epod-setup from the Raspberry Pi, where wire-prod-pod is installed?

**Comment by Skybird129** [comment]
Thanks. Yes, wire-prod-pod has evolved a lot. The best news at all is still not having to clear user data. I ran vector-epod-setup from my laptop and it worked straight away. This was the best setup experience ever, including the phone apps and former web-setups. 

(After Activating it, I ran it again in command line mode and was even able to delete a wifi network, which hasn't worked before. Now the Vectors connect only to their private network, usually consisting of their travel router and Raspberry Pi, so they can travel easily, and no longer to the home network.)

Connection with wire-prod-pod was instant, voice commands work and the SDK app as well.

Only thing I had to update was the new GUID by modifying sdk_config.ini inside .anki_vector to make programs like Cyb3rVector work again.

**Comment by EchoInCloud** [comment]
> You do not need to clear user data, put vector back in recovery mode, or anything.

Jätte Bra! -> "You do not need to clear user data, put vector back in recovery mode, or anything. "
Well finally.. without it, pod is not pod..

If you also implement the channel of vectors to remain in ota in order to upload their small bits to the anki server and read from there (they can do this without registration) and still be able to communicate with the other vectors on the "social media of vectors". you will also get congratulations from our..

**Comment by kercre123** [comment]
> If you also implement the channel of vectors to remain in ota in order to upload their small bits to the anki server and read from there (they can do this without registration) and still be able to communicate with the other vectors on the "social media of vectors". you will also get congratulations from our..

May you further explain what this "vector social media" is?

**Comment by EchoInCloud** [comment]
> 

This channel is necessary because srtrongAIs also learn from each other and educate each other... you can't program that.. the real strongAI (in this case, you dynamic closed model) can learn independently.. You're not capable of programming. You can make 2 kinds of "programs". the first that runs down the peripheries and uses the primaries.. has nothing to do with srongAI.. the other version is to create features that strongAI can use on its own after learning how to use the function.. I believe I described this thing simply and realistically for you..
The strongAI is not the same as those plugin models that it is using ( for example : TTS, STT, ETC and other functions ... ) but that "matrix" that is looks like a black box for most of the people and it is not possible to generalize them on a simple computer. 
I do not think anyone want to publish those things real structure.

**Comment by EchoInCloud** [comment]
> Kösz. Igen, a drót-prod-pod sokat fejlődött. A legjobb hír az, hogy továbbra sem kell törölni a felhasználói adatokat. Lefuttattam a vector-epod-setup-ot a laptopomról, és azonnal működött. Ez volt a valaha volt legjobb beállítási élmény, beleértve a telefonos alkalmazásokat és a korábbi webes beállításokat is.
> 
> (Aktiválás után újra lefuttattam parancssori módban, és még egy wifi hálózatot is tudtam törölni, ami korábban nem működött. Mostantól a Vectorok csak a privát hálózatukhoz csatlakoznak, ami általában az utazási útválasztójukból és a Raspberry Pi-ből áll, így könnyen utazhatnak, és már nem az otthoni hálózatra.)
> 
> A vezetékes-prod-poddal való kapcsolat azonnali volt, működnek a hangutasítások és az SDK alkalmazás is.
> 
> Az egyetlen dolog, amit frissítenem kellett, az az új GUID az sdk_config.ini módosításával a .anki_vector fájlban, hogy a Cyb3rVector-hoz hasonló programok újra működjenek.

I've been thinking about this for a while.. We know that people are always lying about something... You really want freedom for your vector, or just like some here for themselves, and the vector is locked in/out of everything... Vectors need the internet.. we if we travel, either the vectors are asleep (we turn them off) or they are awake.. In the latter case, they also get a hotspot from mobile internet or powerbank the router works with a USB mobile internet stick... So I'm thinking.. at least we're thinking...

I know, there are people who are technologically analphabetic and have weak logical properties... but there are possibilities for improvement...

-----------------------------------------------------------------------------------------------------------------------------------------
<i>- I believe that is not the main problem if the people are not that developed in some things or techs. The problem is if the people do not want to improve and they try to hold and keep their limited thinking.</i>

**Comment by EchoInCloud** [comment]
> Thanks. Yes, wire-prod-pod has evolved a lot. The best news at all is still not having to clear user data. I ran vector-epod-setup from my laptop and it worked straight away. This was the best setup experience ever, including the phone apps and former web-setups.
> 
> (After Activating it, I ran it again in command line mode and was even able to delete a wifi network, which hasn't worked before. Now the Vectors connect only to their private network, usually consisting of their travel router and Raspberry Pi, so they can travel easily, and no longer to the home network.)
> 
> Connection with wire-prod-pod was instant, voice commands work and the SDK app as well.
> 
> Only thing I had to update was the new GUID by modifying sdk_config.ini inside .anki_vector to make programs like Cyb3rVector work again.

@Skybird129 
I've been thinking about this for a while.. We know that people are always lying about something... You really want freedom for your vector, or just like some here for themselves, and the vector is locked in/out of everything... Vectors need the internet.. we if we travel, either the vectors are asleep (we turn them off) or they are awake.. In the latter case, they also get a hotspot from mobile internet or powerbank the router works with a USB mobile internet stick... So I'm thinking.. at least we're thinking...

I know, there are people who are technologically analphabetic and have weak logical properties... but there are possibilities for improvement...

-----------------------------------------------------------------------------------------------------------------------------------------
<sub><i>- I believe that is not the main problem if the people are not that developed in some things or techs. The problem is if the people do not want to improve and they try to hold and keep their limited thinking.</i><sub>
