### ISSUE TITLE
A question about 1.6

### ISSUE THREAD

**Issue by ThommoMC** [kercre123/wire-prod-pod#25]
Would it be possible to redirect a 1.6 Vector's Voice Servers request to Wire-pod? I am aware that programs such as Pi-Hole can send a user specified ip address when requesting a URL but so far, I have been unable to make wire-pod respond to these requests.

**Comment by kercre123** [comment]
This would only be possible if we had the TLS private certificates for the *.api.anki.com endpoints, and we do not have those. We have the ones for the escape pod bot firmware because they have the `escapepod.local` URL embedded in them  and the key for that was extracted from the official escape pod Raspberry Pi image.

**Comment by EchoInCloud** [comment]
The escape pod is already designed for an "unlocked" vector.. Unlocking removes the original "model" structure and modifies the base system integrations used by the model... only the basic plug-in modules remain to run the basic functions...

"if we had the TLS private certificates for the *.api.anki.com endpoints"
That's not how authentication works... authentication is based on the "model" so that no other "foreign model" can be used to retrieve data...
